spring.application.name=backend

app.local-user-email=${LOCAL_USER_EMAIL}

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:keep_in_touch}
spring.datasource.username=${POSTGRES_USER:keep_in_touch}
spring.datasource.password=${POSTGRES_PASSWORD:keep_in_touch}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
